-- ---------------------------------------------------------------------------------------------------
-- EDATOS-3616 - Permitir la búsqueda de territorios por código de elemento de variable
-- ---------------------------------------------------------------------------------------------------

CREATE TABLE TB_GEOCOV_VARELEM_CACHE_DATASETS_VERSIONS (
  DATASET_VERSION_FK BIGINT NOT NULL,
  EXTERNAL_ITEM_FK BIGINT NOT NULL
);

ALTER TABLE TB_GEOCOV_VARELEM_CACHE_DATASETS_VERSIONS ADD CONSTRAINT PK_TB_GEOCOV_VARELEM_CACHE_DATASETS_VERSIONS
	PRIMARY KEY (DATASET_VERSION_FK, EXTERNAL_ITEM_FK)
;

ALTER TABLE TB_GEOCOV_VARELEM_CACHE_DATASETS_VERSIONS ADD CONSTRAINT FK_TB_GEOCOV_VARELEM_CACHE_DATA40
	FOREIGN KEY (DATASET_VERSION_FK) REFERENCES TB_DATASETS_VERSIONS (ID) DEFERRABLE initially IMMEDIATE
;

ALTER TABLE TB_GEOCOV_VARELEM_CACHE_DATASETS_VERSIONS ADD CONSTRAINT FK_TB_GEOCOV_VARELEM_CACHE_DATA91
	FOREIGN KEY (EXTERNAL_ITEM_FK) REFERENCES TB_EXTERNAL_ITEMS (ID) DEFERRABLE initially IMMEDIATE
;

COMMIT;
