-- --------------------------------------------------------------------------------------------------
-- EDATOS-3723 Create columns for data provider information
      -- DATA_PROVIDER
	  -- DATA_PROVIDER_ANNOTATIONS
-- --------------------------------------------------------------------------------------------------

ALTER TABLE TB_STAT_RESOURCES ADD COLUMN DATA_PROVIDER_ANNOTATIONS_FK BIGINT;

CREATE TABLE TB_EI_DATA_PROVIDERS (
  DATA_PROVIDER_FK BIGINT NOT NULL,
  SIEMAC_RESOURCE_FK BIGINT NOT NULL
);

ALTER TABLE TB_EI_DATA_PROVIDERS ADD CONSTRAINT PK_TB_EI_DATA_PROVIDERS
	PRIMARY KEY (DATA_PROVIDER_FK, SIEMAC_RESOURCE_FK)
;

ALTER TABLE TB_EI_DATA_PROVIDERS ADD CONSTRAINT FK_TB_EI_DATA_PROVIDERS_DATA_PROVIDER_FK
	FOREIGN KEY (DATA_PROVIDER_FK) REFERENCES TB_EXTERNAL_ITEMS (ID) DEFERRABLE initially IMMEDIATE
;

ALTER TABLE TB_EI_DATA_PROVIDERS ADD CONSTRAINT FK_TB_EI_DATA_PROVIDERS_SIEMAC_RESOURCE_FK
	FOREIGN KEY (SIEMAC_RESOURCE_FK) REFERENCES TB_STAT_RESOURCES (ID) DEFERRABLE initially IMMEDIATE
;

commit;