-------------------------------------------------------------------------------------------------------------------------
-- -- DESARROLLO, PRE & PRO IESTADIS E IBESTAT
-- ------------------------------------------------------------------------------------------------------------------------
-- 
-- CREATE SCHEMA extensions;
-- 
-- -- Extension 'unaccent' needs to be created, a superuser or user with create privilege should execute the following:
-- -- (unaccent is a trusted extension)
-- CREATE extension unaccent WITH SCHEMA extensions;
-- 
-- -- Make sure metamac_structural_resources_bd and metamac_structural_resources_own_bd can use everything in the extensions schema
-- GRANT USAGE ON SCHEMA extensions TO public;
-- GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA extensions TO metamac_statistical_resources_bd, metamac_statistical_resources_data_bd,
--                      metamac_statistical_resources_own_bd, metamac_statistical_resources_data_own_bd;
-- 
-- -- Include future extensions
-- ALTER DEFAULT PRIVILEGES IN SCHEMA extensions
-- GRANT EXECUTE ON FUNCTIONS TO metamac_statistical_resources_bd, metamac_statistical_resources_data_bd,
--                      metamac_statistical_resources_own_bd, metamac_statistical_resources_data_own_bd;
-- 
-- ALTER DEFAULT PRIVILEGES IN SCHEMA extensions
-- GRANT USAGE ON TYPES TO metamac_statistical_resources_bd, metamac_statistical_resources_data_bd,
--                      metamac_statistical_resources_own_bd, metamac_statistical_resources_data_own_bd;
-- 
-- -- Check the current search_path
-- -- SHOW search_path;
-- 
-- ALTER DATABASE metamac_statistical_resources_bd SET search_path TO FILL_CURRENT_SEARCH_PATH, extensions;
-- ALTER DATABASE metamac_statistical_resources_data_bd SET search_path TO FILL_CURRENT_SEARCH_PATH, extensions;
-- 
-- ------------------------------------------------------------------------------------------------------------------------
-- -- DEMO, PRE & PRO ISTAC
-- ------------------------------------------------------------------------------------------------------------------------
-- 
-- CREATE SCHEMA extensions;
-- 
-- -- Extension 'unaccent' needs to be created, a superuser or user with create privilege should execute the following:
-- -- (unaccent is a trusted extension)
-- CREATE extension unaccent WITH SCHEMA extensions;
-- 
-- -- Make sure istac_statistical_resources_bd and istac_statistical_resources_own_bd can use everything in the extensions schema
-- GRANT USAGE ON SCHEMA extensions TO public;
-- GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA extensions TO istac_statistical_resources_bd, istac_statistical_resources_own_bd;
-- 
-- -- Include future extensions
-- ALTER DEFAULT PRIVILEGES IN SCHEMA extensions
-- GRANT EXECUTE ON FUNCTIONS TO istac_statistical_resources_bd, istac_statistical_resources_own_bd;
-- 
-- ALTER DEFAULT PRIVILEGES IN SCHEMA extensions
-- GRANT USAGE ON TYPES TO istac_statistical_resources_bd, istac_statistical_resources_own_bd;
-- 
-- DO $$
-- DECLARE
-- current_search_path TEXT;
-- BEGIN
--     -- Obtén el search_path actual
-- SELECT current_setting('search_path') INTO current_search_path;
-- 
-- -- Genera el nuevo search_path y actualiza la base de datos
-- EXECUTE format('ALTER DATABASE "istac_statistical_resources_bd" SET search_path = %s, extensions', current_search_path
--         );
-- END $$;
-- 
-- GRANT USAGE ON SCHEMA extensions TO public;
-- GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA extensions TO istac_statistical_resources_data_bd, istac_statistical_resources_data_own_bd;
-- 
-- -- Include future extensions
-- ALTER DEFAULT PRIVILEGES IN SCHEMA extensions
-- GRANT EXECUTE ON FUNCTIONS TO istac_statistical_resources_data_bd, istac_statistical_resources_data_own_bd;
-- 
-- ALTER DEFAULT PRIVILEGES IN SCHEMA extensions
-- GRANT USAGE ON TYPES TO istac_statistical_resources_data_bd, istac_statistical_resources_data_own_bd;
-- 
-- DO $$
-- DECLARE
-- current_search_path TEXT;
-- BEGIN
--     -- Obtén el search_path actual
-- SELECT current_setting('search_path') INTO current_search_path;
-- 
-- -- Genera el nuevo search_path y actualiza la base de datos
-- EXECUTE format('ALTER DATABASE "istac_statistical_resources_data_bd" SET search_path = %s, extensions', current_search_path
--         );
-- END $$;
-- 
--

-- ------------------------------------------------------------------------------------------------------------------------
-- -- CI DATABASE --
-- ------------------------------------------------------------------------------------------------------------------------
--
-- CREATE SCHEMA extensions;
--
-- -- Extension 'unaccent' needs to be created, a superuser or user with create privilege should execute the following:
-- -- (unaccent is a trusted extension)
-- CREATE extension unaccent WITH SCHEMA extensions;
--
-- -- Make sure istac_statistical_resources_bd and istac_statistical_resources_own_bd can use everything in the extensions schema
-- GRANT USAGE ON SCHEMA extensions TO public;
-- GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA extensions TO istac_metamac_stat_res_repo_ci, istac_metamac_stat_resources_ci;
--
-- -- Include future extensions
-- ALTER DEFAULT PRIVILEGES IN SCHEMA extensions
-- GRANT EXECUTE ON FUNCTIONS TO istac_metamac_stat_res_repo_ci, istac_metamac_stat_resources_ci;
--
-- ALTER DEFAULT PRIVILEGES IN SCHEMA extensions
-- GRANT USAGE ON TYPES TO istac_metamac_stat_res_repo_ci, istac_metamac_stat_resources_ci;

-- -- usuario: istac_metamac_stat_resources_ci
-- -- search_path por defecto: istac_metamac_stat_resources_ci, istac_metamac_stat_resources_ci, "$user"
-- ALTER ROLE istac_metamac_stat_resources_ci SET search_path TO istac_metamac_stat_resources_ci, extensions, "$user";