<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.siemac.metamac.metamac-statistical-resources</groupId>
		<artifactId>metamac-statistical-resources-parent</artifactId>
		<version>11.3.2-SNAPSHOT</version>
		<relativePath>../metamac-statistical-resources-parent/pom.xml</relativePath>
	</parent>

	<groupId>org.siemac.metamac.metamac-statistical-resources</groupId>
	<artifactId>metamac-statistical-resources-rest-common-impl</artifactId>
	<packaging>jar</packaging>
	<name>METAMAC :: STATISTICAL RESOURCES :: REST :: COMMON IMPL</name>
	<description>METAMAC :: STATISTICAL RESOURCES :: REST :: COMMON IMPL</description>


	<dependencies>
		<dependency>
			<groupId>org.siemac.metamac</groupId>
			<artifactId>metamac-rest-api</artifactId>
			<version>${metamac-rest-api.version}</version>
		</dependency>
		<dependency>
			<groupId>org.siemac.metamac.metamac-statistical-resources</groupId>
			<artifactId>metamac-statistical-resources-core</artifactId>
			<classifier>client</classifier>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>org.siemac.metamac.metamac-statistical-resources</groupId>
			<artifactId>metamac-statistical-resources-rest-api-common</artifactId>
			<version>${metamac-statistical-resources-rest-api-common.version}</version>
		</dependency>
		<dependency>
			<groupId>org.siemac.metamac</groupId>
			<artifactId>metamac-core-common</artifactId>
			<version>${metamac-core-common.version}</version>
		</dependency>
		<dependency>
			<groupId>org.siemac.metamac</groupId>
			<artifactId>metamac-rest-common</artifactId>
			<version>${metamac-rest-common.version}</version>
		</dependency>
		<dependency>
			<groupId>commons-lang</groupId>
			<artifactId>commons-lang</artifactId>
			<version>${commons-lang.version}</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>log4j-over-slf4j</artifactId>
			<version>${slf4j.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.cxf.xjc-utils</groupId>
			<artifactId>cxf-xjc-runtime</artifactId>
			<version>${cxf.version}</version>
		</dependency>
	</dependencies>

	<profiles>
		<profile>
			<id>include-tests-dependencies</id>
			<activation>
				<property>
					<name>maven.test.skip</name>
					<value>!true</value>
				</property>
			</activation>
			<dependencies>
				<!-- Test -->
				<dependency>
					<groupId>junit</groupId>
					<artifactId>junit</artifactId>
					<version>${junit.version}</version>
					<scope>test</scope>
				</dependency>
			</dependencies>
		</profile>
	</profiles>
	<build>
		<finalName>${project.artifactId}</finalName>
		<plugins>
			<plugin>
				<artifactId>maven-clean-plugin</artifactId>
				<version>2.4.1</version>
				<configuration>
					<filesets>
						<fileset>
							<directory>src/generated</directory>
							<includes>
								<include>**/*.java</include>
								<include>**/*.xml</include>
								<include>**/*.properties</include>
								<include>**/*.dot</include>
							</includes>
							<excludes>
								<exclude>**/.svn/*</exclude>
							</excludes>
							<followSymlinks>false</followSymlinks>
						</fileset>
						<fileset>
							<directory>src/test/generated</directory>
							<includes>
								<include>**/*.java</include>
								<include>**/*.xml</include>
								<include>**/*.properties</include>
							</includes>
							<excludes>
								<exclude>**/.svn/*</exclude>
							</excludes>
							<followSymlinks>false</followSymlinks>
						</fileset>
					</filesets>
				</configuration>
			</plugin>
			<plugin>
				<artifactId>maven-jar-plugin</artifactId>
				<version>2.3.1</version>
				<executions>
					<execution>
						<goals>
							<goal>test-jar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
