<?xml version="1.0" encoding="UTF-8"?>
<xs:schema version="1.0"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified"
	targetNamespace="http://www.siemac.org/metamac/rest/statistical-resources-internal/v1.0/domain"
	xmlns:tns="http://www.siemac.org/metamac/rest/statistical-resources-internal/v1.0/domain"
	xmlns:common="http://www.siemac.org/metamac/rest/common/v1.0/domain"
	xmlns:common-tns="http://www.siemac.org/metamac/statistical-resources/rest/common/v1.0/domain">

	<xs:import
		namespace="http://www.siemac.org/metamac/rest/common/v1.0/domain"
		schemaLocation="metamac-rest-api:metamac-rest-common-domain-v1.0.xsd" />
	<xs:import
		namespace="http://www.siemac.org/metamac/statistical-resources/rest/common/v1.0/domain"
		schemaLocation="metamac-statistical-resources-rest-api-common-domain-v1.0.xsd" />


	<xs:complexType name="Dataset">
		<xs:complexContent>
			<xs:extension base="common-tns:DatasetBase">
				<xs:sequence>
					<xs:element name="managementAppLink" type="xs:string" />
					<xs:element name="metadata" type="tns:DatasetMetadata" minOccurs="0"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="Collection">
		<xs:complexContent>
			<xs:extension base="common-tns:CollectionBase">
				<xs:sequence>
					<xs:element name="managementAppLink" type="xs:string" />
					<xs:element name="metadata" type="tns:CollectionMetadata" minOccurs="0" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="Query">
		<xs:complexContent>
			<xs:extension base="common-tns:QueryBase">
				<xs:sequence>
					<xs:element name="managementAppLink" type="xs:string" />
					<xs:element name="metadata" type="tns:QueryMetadata" minOccurs="0" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="Multidataset">
		<xs:complexContent>
			<xs:extension base="common-tns:MultidatasetBase">
				<xs:sequence>
					<xs:element name="managementAppLink" type="xs:string" />
					<xs:element name="metadata" type="tns:MultidatasetMetadata" minOccurs="0" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="QueryMetadata">
		<xs:complexContent>
			<xs:extension base="common-tns:QueryMetadataBase">
				<xs:sequence>
					<xs:element name="nextVersion"
						type="common-tns:NextVersionType" />
					<xs:element name="nextVersionDate"
						type="common:InternationalString" minOccurs="0" />
					<xs:element name="procStatus"
						type="common-tns:ProcStatusType" />
					<xs:element name="creationDate" type="xs:dateTime"
						minOccurs="0" />
					<xs:element name="creationUser" type="xs:string"
						minOccurs="0" />
					<xs:element name="productionValidationDate"
						type="xs:dateTime" minOccurs="0" />
					<xs:element name="productionValidationUser"
						type="xs:string" minOccurs="0" />
					<xs:element name="diffusionValidationDate"
						type="xs:dateTime" minOccurs="0" />
					<xs:element name="diffusionValidationUser"
						type="xs:string" minOccurs="0" />
					<xs:element name="rejectValidationDate"
						type="xs:dateTime" minOccurs="0" />
					<xs:element name="rejectValidationUser" type="xs:string"
						minOccurs="0" />
					<xs:element name="publicationDate" type="xs:dateTime"
						minOccurs="0" />
					<xs:element name="publicationUser" type="xs:string"
						minOccurs="0" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:group name="StatisticalResourceExtended">
		<xs:sequence>
			<xs:element name="nextVersionDate"
				type="common:InternationalString" minOccurs="0" />
			<xs:element name="procStatus"
				type="common-tns:ProcStatusType" />
			<xs:element name="creationDate" type="xs:dateTime"
				minOccurs="0" />
			<xs:element name="creationUser" type="xs:string"
				minOccurs="0" />
			<xs:element name="productionValidationDate"
				type="xs:dateTime" minOccurs="0" />
			<xs:element name="productionValidationUser"
				type="xs:string" minOccurs="0" />
			<xs:element name="diffusionValidationDate"
				type="xs:dateTime" minOccurs="0" />
			<xs:element name="diffusionValidationUser"
				type="xs:string" minOccurs="0" />
			<xs:element name="rejectValidationDate" type="xs:dateTime"
				minOccurs="0" />
			<xs:element name="rejectValidationUser" type="xs:string"
				minOccurs="0" />
			<xs:element name="publicationDate" type="xs:dateTime"
				minOccurs="0" />
			<xs:element name="publicationUser" type="xs:string"
				minOccurs="0" />
			<xs:element name="conformsToInternal"
				type="common:InternationalString" minOccurs="0" />
		</xs:sequence>
	</xs:group>
	
	<xs:complexType name="DatasetMetadata">
		<xs:complexContent>
			<xs:extension base="common-tns:DatasetMetadataBase">
			<xs:group ref="tns:StatisticalResourceExtended"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="CollectionMetadata">
		<xs:complexContent>
			<xs:extension base="common-tns:CollectionMetadataBase">
			<xs:group ref="tns:StatisticalResourceExtended"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="MultidatasetMetadata">
		<xs:complexContent>
			<xs:extension base="common-tns:MultidatasetMetadataBase">
			<xs:group ref="tns:StatisticalResourceExtended"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:simpleType name="QueryCriteriaPropertyRestriction">
		<xs:restriction base="xs:token">
			<xs:enumeration value="ID" />
			<xs:enumeration value="NAME" />
			<xs:enumeration value="DESCRIPTION" />
			<xs:enumeration value="RELATED_DATASET_URN" />
			<xs:enumeration value="STATUS" />
			<xs:enumeration value="TYPE" />
			<xs:enumeration value="VALID_FROM" />
			<xs:enumeration value="VALID_TO" />
			<xs:enumeration value="STATISTICAL_OPERATION_URN" />
			<xs:enumeration value="PROC_STATUS" />
		</xs:restriction>
	</xs:simpleType>

  <!-- Elements -->
    <xs:element name="dataset" type="tns:Dataset" />
    <xs:element name="collection" type="tns:Collection" />
    <xs:element name="query" type="tns:Query" />
    <xs:element name="multidataset" type="tns:Multidataset" />
</xs:schema>
