CREATE sequence SEQ_TERRITORIES_CACHE;

CREATE TABLE TB_TERRITORIES_CACHE (
  ID NUMBER(19) NOT NULL,
  CREATED_DATE_TZ VARCHAR2(50 CHAR),
  CREATED_DATE TIMESTAMP,
  CREATED_BY VARCHAR2(50 CHAR),
  LAST_UPDATED_TZ VARCHAR2(50 CHAR),
  LAST_UPDATED TIMESTAMP,
  LAST_UPDATED_BY VARCHAR2(50 CHAR),
  VERSION NUMBER(19) NOT NULL,
  VARIABLE_ELEMENT_FK NUMBER(19)
);

CREATE TABLE TB_TERRITORIES_CACHE_DATASETS_VERSIONS (
  DATASET_VERSION_FK NUMBER(19) NOT NULL,
  TERRITORY_FK NUMBER(19) NOT NULL
);

ALTER TABLE TB_TERRITORIES_CACHE ADD CONSTRAINT PK_TB_TERRITORIES_CACHE
	PRIMARY KEY (ID)
;

ALTER TABLE TB_TERRITORIES_CACHE_DATASETS_VERSIONS ADD CONSTRAINT PK_TB_TERRITORIES_CACHE_DATASETS_VERSIONS
	PRIMARY KEY (DATASET_VERSION_FK, TERRITORY_FK)
;

ALTER TABLE TB_TERRITORIES_CACHE
	ADD CONSTRAINT UQ_TB_TERRITORIES_CACHE UNIQUE (ID)
;

ALTER TABLE TB_TERRITORIES_CACHE ADD CONSTRAINT FK_TB_TERRITORIES_CACHE_VARI82
	FOREIGN KEY (VARIABLE_ELEMENT_FK) REFERENCES TB_EXTERNAL_ITEMS (ID) DEFERRABLE initially IMMEDIATE
;

ALTER TABLE TB_TERRITORIES_CACHE_DATASETS_VERSIONS ADD CONSTRAINT FK_TB_TERRITORIES_CACHE_DATA40
	FOREIGN KEY (DATASET_VERSION_FK) REFERENCES TB_DATASETS_VERSIONS (ID) DEFERRABLE initially IMMEDIATE
;

ALTER TABLE TB_TERRITORIES_CACHE_DATASETS_VERSIONS ADD CONSTRAINT FK_TB_TERRITORIES_CACHE_DATA91
	FOREIGN KEY (TERRITORY_FK) REFERENCES TB_TERRITORIES_CACHE (ID) DEFERRABLE initially IMMEDIATE
;

COMMIT;
